#ifndef CONFIG_H
#define CONFIG_H

#include <linux/version.h>

//
#if LINUX_VERSION_CODE > KERNEL_VERSION(3, 11, 0)
	#define CONFIG_BDICONFIG_BDI
#endif

#if LINUX_VERSION_CODE > KERNEL_VERSION(3, 11, 0)
#else
	#define CONFIG_VFS_UNLINK_3_PARAM
#endif

#if LINUX_VERSION_CODE <  KERNEL_VERSION(3, 11, 0)
	#define CONFIG_ITERATE_DIR 
#endif

#if LINUX_VERSION_CODE < KERNEL_VERSION(3, 11, 0)
	#define CONFIG_VFS_LINK_4_PARAM
#endif

#if LINUX_VERSION_CODE < KERNEL_VERSION(3, 11, 0)
#define CONFIG_VFS_UNLINK_4_PARAM
#endif

#if LINUX_VERSION_CODE < KERNEL_VERSION(3, 11, 0)
#define CONFIG_VFS_RENAME_6_PARAM
#endif


#endif // !CONFIG_H
